"""Reply templates for the deterministic tiers, per reply language.

Romanized Telugu/Bengali and languages without a template set fall back to English."""

from __future__ import annotations

KEYS = (
    "greet", "menu_header", "added", "price", "not_found", "ambiguous", "cart_empty", "cart", "order_placed_upi",
    "order_placed_cod", "paid_claimed", "status", "no_orders", "hours", "location", "human", "cancelled",
    "cart_cleared", "cannot_cancel", "removed", "thanks", "fallback", "out_of_stock", "no_info",
)

STATUS_KEYS = ("pending_payment", "payment_claimed", "paid", "preparing", "ready", "delivered", "cancelled")

T: dict[str, dict[str, str]] = {
    "en": {
        "greet": "Namaste! Welcome to {biz}. Tell me what you need, for example '2 kg sugar'. Type 'menu' to see everything.",
        "menu_header": "Here's what {biz} has:",
        "added": "Added {items}. Cart total: {total}. Say 'confirm' to place the order.",
        "price": "{name} is {price} per {unit}.",
        "not_found": "Sorry, I couldn't find that. Type 'menu' to see what we have.",
        "ambiguous": "Which one do you mean? {options}",
        "cart_empty": "Your cart is empty. Tell me what you'd like.",
        "cart": "Your cart: {items}. Total: {total}. Say 'confirm' to order.",
        "order_placed_upi": "Order {code} placed. Total {total}. Pay by UPI with the button below; {biz} will confirm once the money arrives.",
        "order_placed_cod": "Order {code} placed. Total {total}. Please pay {biz} on delivery.",
        "paid_claimed": "Thank you! I've told {biz} that you paid for order {code}. They'll confirm shortly.",
        "status": "Order {code}: {status}.",
        "no_orders": "You don't have any orders with us yet.",
        "hours": "{biz} is open {hours}.",
        "location": "{biz} address: {address}",
        "human": "I've asked the owner to reply. They'll get back to you here soon.",
        "cancelled": "Order {code} is cancelled.",
        "cart_cleared": "Okay, I've cleared your cart.",
        "cannot_cancel": "Order {code} is already {status}; please ask the owner.",
        "removed": "Removed {items}. Cart total: {total}.",
        "thanks": "Thank you! Do come again.",
        "fallback": "Sorry, I didn't get that. You can say things like '2 kg sugar', 'menu' or 'talk to owner'.",
        "out_of_stock": "Sorry, {name} is out of stock right now.",
        "no_info": "I don't have that information; I've asked the owner.",
    },
    "hi": {
        "greet": "नमस्ते! {biz} में आपका स्वागत है। आपको क्या चाहिए, बताइए — जैसे '2 किलो चीनी'। सामान देखने के लिए 'मेनू' लिखें।",
        "menu_header": "{biz} में यह सब मिलता है:",
        "added": "{items} जोड़ दिया। कार्ट का कुल: {total}। ऑर्डर करने के लिए 'कन्फर्म' लिखें।",
        "price": "{name} का दाम {price} प्रति {unit} है।",
        "not_found": "माफ़ कीजिए, यह नहीं मिला। सामान देखने के लिए 'मेनू' लिखें।",
        "ambiguous": "आप कौन सा चाहते हैं? {options}",
        "cart_empty": "आपका कार्ट खाली है। बताइए क्या चाहिए।",
        "cart": "आपका कार्ट: {items}। कुल: {total}। ऑर्डर के लिए 'कन्फर्म' लिखें।",
        "order_placed_upi": "ऑर्डर {code} हो गया। कुल {total}। नीचे दिए बटन से UPI पर भुगतान करें; पैसे मिलने पर {biz} पुष्टि करेगा।",
        "order_placed_cod": "ऑर्डर {code} हो गया। कुल {total}। डिलीवरी पर {biz} को भुगतान करें।",
        "paid_claimed": "धन्यवाद! मैंने {biz} को बता दिया है कि आपने ऑर्डर {code} का भुगतान कर दिया है। वे जल्द पुष्टि करेंगे।",
        "status": "ऑर्डर {code}: {status}।",
        "no_orders": "अभी आपका कोई ऑर्डर नहीं है।",
        "hours": "{biz} का समय: {hours}।",
        "location": "{biz} का पता: {address}",
        "human": "मैंने मालिक को जवाब देने के लिए कह दिया है। वे जल्द यहीं जवाब देंगे।",
        "cancelled": "ऑर्डर {code} रद्द कर दिया गया है।",
        "cart_cleared": "ठीक है, आपका कार्ट खाली कर दिया।",
        "cannot_cancel": "ऑर्डर {code} अब {status} है; कृपया मालिक से बात करें।",
        "removed": "{items} हटा दिया। कार्ट का कुल: {total}।",
        "thanks": "धन्यवाद! फिर आइएगा।",
        "fallback": "माफ़ कीजिए, समझ नहीं आया। आप ऐसे लिख सकते हैं: '2 किलो चीनी', 'मेनू', या 'मालिक से बात'।",
        "out_of_stock": "माफ़ कीजिए, {name} अभी स्टॉक में नहीं है।",
        "no_info": "यह जानकारी मेरे पास नहीं है; मैंने मालिक को बता दिया है।",
    },
    "hi_latn": {
        "greet": "Namaste! {biz} mein aapka swagat hai. Kya chahiye bataiye, jaise '2 kilo cheeni'. Saaman dekhne ke liye 'menu' likhiye.",
        "menu_header": "{biz} mein ye sab milta hai:",
        "added": "{items} add kar diya. Cart total: {total}. Order ke liye 'confirm' likhiye.",
        "price": "{name} ka daam {price} per {unit} hai.",
        "not_found": "Maaf kijiye, ye nahi mila. Saaman dekhne ke liye 'menu' likhiye.",
        "ambiguous": "Aap kaun sa chahte hain? {options}",
        "cart_empty": "Aapka cart khaali hai. Bataiye kya chahiye.",
        "cart": "Aapka cart: {items}. Total: {total}. Order ke liye 'confirm' likhiye.",
        "order_placed_upi": "Order {code} ho gaya. Total {total}. Neeche diye button se UPI payment kijiye; paise milne par {biz} confirm karega.",
        "order_placed_cod": "Order {code} ho gaya. Total {total}. Delivery par {biz} ko payment kijiye.",
        "paid_claimed": "Shukriya! Maine {biz} ko bata diya ki aapne order {code} ka payment kar diya hai. Woh jaldi confirm karenge.",
        "status": "Order {code}: {status}.",
        "no_orders": "Abhi aapka koi order nahi hai.",
        "hours": "{biz} ka time: {hours}.",
        "location": "{biz} ka address: {address}",
        "human": "Maine owner ko reply karne ke liye bol diya hai. Woh jaldi yahin reply karenge.",
        "cancelled": "Order {code} cancel kar diya gaya hai.",
        "cart_cleared": "Theek hai, cart khaali kar diya.",
        "cannot_cancel": "Order {code} ab {status} hai; owner se baat kijiye.",
        "removed": "{items} hata diya. Cart total: {total}.",
        "thanks": "Dhanyavaad! Phir aaiyega.",
        "fallback": "Maaf kijiye, samajh nahi aaya. Aap aise likh sakte hain: '2 kilo cheeni', 'menu', ya 'owner se baat'.",
        "out_of_stock": "Maaf kijiye, {name} abhi stock mein nahi hai.",
        "no_info": "Ye jaankari mere paas nahi hai; maine owner ko bata diya hai.",
    },
    "mr": {
        "greet": "नमस्कार! {biz} मध्ये आपले स्वागत आहे. काय हवे ते सांगा — उदा. '2 किलो साखर'. सामान पाहण्यासाठी 'मेनू' लिहा.",
        "menu_header": "{biz} मध्ये हे मिळते:",
        "added": "{items} जोडले. कार्टची एकूण रक्कम: {total}. ऑर्डरसाठी 'कन्फर्म' लिहा.",
        "price": "{name} ची किंमत {price} प्रति {unit} आहे.",
        "not_found": "माफ करा, हे सापडले नाही. सामान पाहण्यासाठी 'मेनू' लिहा.",
        "ambiguous": "तुम्हाला कोणते हवे? {options}",
        "cart_empty": "तुमचे कार्ट रिकामे आहे. काय हवे ते सांगा.",
        "cart": "तुमचे कार्ट: {items}. एकूण: {total}. ऑर्डरसाठी 'कन्फर्म' लिहा.",
        "order_placed_upi": "ऑर्डर {code} झाली. एकूण {total}. खालील बटणाने UPI द्वारे पैसे भरा; पैसे मिळाल्यावर {biz} पुष्टी करेल.",
        "order_placed_cod": "ऑर्डर {code} झाली. एकूण {total}. डिलिव्हरीवेळी {biz} ला पैसे द्या.",
        "paid_claimed": "धन्यवाद! तुम्ही ऑर्डर {code} चे पैसे भरल्याचे मी {biz} ला कळवले आहे. ते लवकरच पुष्टी करतील.",
        "status": "ऑर्डर {code}: {status}.",
        "no_orders": "तुमची अजून कोणतीही ऑर्डर नाही.",
        "hours": "{biz} ची वेळ: {hours}.",
        "location": "{biz} चा पत्ता: {address}",
        "human": "मी मालकांना उत्तर देण्यास सांगितले आहे. ते लवकरच इथे उत्तर देतील.",
        "cancelled": "ऑर्डर {code} रद्द केली आहे.",
        "cart_cleared": "ठीक आहे, कार्ट रिकामे केले.",
        "cannot_cancel": "ऑर्डर {code} आता {status} आहे; कृपया मालकांशी बोला.",
        "removed": "{items} काढले. कार्टची एकूण रक्कम: {total}.",
        "thanks": "धन्यवाद! पुन्हा या.",
        "fallback": "माफ करा, समजले नाही. तुम्ही असे लिहू शकता: '2 किलो साखर', 'मेनू', किंवा 'मालकांशी बोलायचे आहे'.",
        "out_of_stock": "माफ करा, {name} सध्या उपलब्ध नाही.",
        "no_info": "ही माहिती माझ्याकडे नाही; मी मालकांना कळवले आहे.",
    },
    "ta": {
        "greet": "வணக்கம்! {biz}-க்கு வரவேற்கிறோம். உங்களுக்கு என்ன வேண்டும் என்று சொல்லுங்கள் — எ.கா. '2 கிலோ சர்க்கரை'. பொருட்களைப் பார்க்க 'menu' என்று அனுப்புங்கள்.",
        "menu_header": "{biz}-இல் கிடைப்பவை:",
        "added": "{items} சேர்க்கப்பட்டது. மொத்தம்: {total}. ஆர்டர் செய்ய 'confirm' என்று அனுப்புங்கள்.",
        "price": "{name} விலை ஒரு {unit}-க்கு {price}.",
        "not_found": "மன்னிக்கவும், அது கிடைக்கவில்லை. பொருட்களைப் பார்க்க 'menu' என்று அனுப்புங்கள்.",
        "ambiguous": "எதைக் கேட்கிறீர்கள்? {options}",
        "cart_empty": "உங்கள் கூடை காலியாக உள்ளது. என்ன வேண்டும் என்று சொல்லுங்கள்.",
        "cart": "உங்கள் கூடை: {items}. மொத்தம்: {total}. ஆர்டர் செய்ய 'confirm' என்று அனுப்புங்கள்.",
        "order_placed_upi": "ஆர்டர் {code} பதிவானது. மொத்தம் {total}. கீழே உள்ள பொத்தானில் UPI மூலம் செலுத்துங்கள்; பணம் வந்ததும் {biz} உறுதிசெய்யும்.",
        "order_placed_cod": "ஆர்டர் {code} பதிவானது. மொத்தம் {total}. டெலிவரியின்போது {biz}-க்குப் பணம் செலுத்துங்கள்.",
        "paid_claimed": "நன்றி! ஆர்டர் {code}-க்கு நீங்கள் பணம் செலுத்தியதை {biz}-க்குத் தெரிவித்துவிட்டேன். அவர்கள் விரைவில் உறுதிசெய்வார்கள்.",
        "status": "ஆர்டர் {code}: {status}.",
        "no_orders": "உங்களுக்கு இன்னும் ஆர்டர் எதுவும் இல்லை.",
        "hours": "{biz} நேரம்: {hours}.",
        "location": "{biz} முகவரி: {address}",
        "human": "உரிமையாளரிடம் பதில் அளிக்கச் சொல்லியிருக்கிறேன். அவர் விரைவில் இங்கே பதில் அளிப்பார்.",
        "cancelled": "ஆர்டர் {code} ரத்து செய்யப்பட்டது.",
        "cart_cleared": "சரி, கூடையைக் காலி செய்துவிட்டேன்.",
        "cannot_cancel": "ஆர்டர் {code} ஏற்கனவே {status}; உரிமையாளரிடம் கேளுங்கள்.",
        "removed": "{items} நீக்கப்பட்டது. மொத்தம்: {total}.",
        "thanks": "நன்றி! மீண்டும் வாருங்கள்.",
        "fallback": "மன்னிக்கவும், புரியவில்லை. '2 கிலோ சர்க்கரை', 'menu', அல்லது 'உரிமையாளர்' என்று அனுப்பலாம்.",
        "out_of_stock": "மன்னிக்கவும், {name} இப்போது இருப்பில் இல்லை.",
        "no_info": "அந்தத் தகவல் என்னிடம் இல்லை; உரிமையாளரிடம் தெரிவித்துவிட்டேன்.",
    },
    "ta_latn": {
        "greet": "Vanakkam! {biz}-ku varaverkirom. Ungalukku enna venum nu sollunga, e.g. '2 kilo sakkarai'. Items paakka 'menu' nu anuppunga.",
        "menu_header": "{biz}-la kidaikkaradhu:",
        "added": "{items} add pannitten. Total: {total}. Order panna 'confirm' nu anuppunga.",
        "price": "{name} vilai oru {unit}-ku {price}.",
        "not_found": "Mannikkavum, adhu kidaikkala. Items paakka 'menu' nu anuppunga.",
        "ambiguous": "Edhu venum? {options}",
        "cart_empty": "Unga cart kaali-ya irukku. Enna venum nu sollunga.",
        "cart": "Unga cart: {items}. Total: {total}. Order panna 'confirm' nu anuppunga.",
        "order_placed_upi": "Order {code} aachu. Total {total}. Keezha irukkura button-la UPI-la pay pannunga; panam vandhadhum {biz} confirm pannuvanga.",
        "order_placed_cod": "Order {code} aachu. Total {total}. Delivery-appo {biz}-ku pay pannunga.",
        "paid_claimed": "Nandri! Order {code}-ku neenga pay pannadha {biz}-ku sollitten. Seekiram confirm pannuvanga.",
        "status": "Order {code}: {status}.",
        "no_orders": "Ungalukku innum order edhuvum illa.",
        "hours": "{biz} time: {hours}.",
        "location": "{biz} address: {address}",
        "human": "Owner-kitta reply panna sollirukken. Seekiram inga reply pannuvanga.",
        "cancelled": "Order {code} cancel aayiduchu.",
        "cart_cleared": "Sari, cart-a kaali pannitten.",
        "cannot_cancel": "Order {code} already {status}; owner-kitta kelunga.",
        "removed": "{items} remove pannitten. Total: {total}.",
        "thanks": "Nandri! Thirumba vaanga.",
        "fallback": "Mannikkavum, puriyala. '2 kilo sakkarai', 'menu', illa 'owner' nu anuppalaam.",
        "out_of_stock": "Mannikkavum, {name} ippo stock-la illa.",
        "no_info": "Andha information ennakitta illa; owner-kitta sollitten.",
    },
    "te": {
        "greet": "నమస్కారం! {biz}కి స్వాగతం. మీకు ఏం కావాలో చెప్పండి — ఉదా. '2 కిలో చక్కెర'. సరుకులు చూడటానికి 'menu' అని పంపండి.",
        "menu_header": "{biz}లో దొరికేవి:",
        "added": "{items} చేర్చాను. మొత్తం: {total}. ఆర్డర్ చేయడానికి 'confirm' అని పంపండి.",
        "price": "{name} ధర ఒక {unit}కి {price}.",
        "not_found": "క్షమించండి, అది దొరకలేదు. సరుకులు చూడటానికి 'menu' అని పంపండి.",
        "ambiguous": "మీకు ఏది కావాలి? {options}",
        "cart_empty": "మీ కార్ట్ ఖాళీగా ఉంది. ఏం కావాలో చెప్పండి.",
        "cart": "మీ కార్ట్: {items}. మొత్తం: {total}. ఆర్డర్ చేయడానికి 'confirm' అని పంపండి.",
        "order_placed_upi": "ఆర్డర్ {code} నమోదైంది. మొత్తం {total}. కింది బటన్‌తో UPI ద్వారా చెల్లించండి; డబ్బు అందగానే {biz} నిర్ధారిస్తుంది.",
        "order_placed_cod": "ఆర్డర్ {code} నమోదైంది. మొత్తం {total}. డెలివరీ సమయంలో {biz}కి చెల్లించండి.",
        "paid_claimed": "ధన్యవాదాలు! ఆర్డర్ {code}కి మీరు చెల్లించారని {biz}కి తెలియజేశాను. వారు త్వరలో నిర్ధారిస్తారు.",
        "status": "ఆర్డర్ {code}: {status}.",
        "no_orders": "మీకు ఇంకా ఆర్డర్లు ఏమీ లేవు.",
        "hours": "{biz} సమయం: {hours}.",
        "location": "{biz} చిరునామా: {address}",
        "human": "యజమానిని జవాబు ఇవ్వమని చెప్పాను. వారు త్వరలో ఇక్కడే జవాబిస్తారు.",
        "cancelled": "ఆర్డర్ {code} రద్దు చేయబడింది.",
        "cart_cleared": "సరే, కార్ట్ ఖాళీ చేశాను.",
        "cannot_cancel": "ఆర్డర్ {code} ఇప్పటికే {status}; దయచేసి యజమానిని అడగండి.",
        "removed": "{items} తీసేశాను. మొత్తం: {total}.",
        "thanks": "ధన్యవాదాలు! మళ్ళీ రండి.",
        "fallback": "క్షమించండి, అర్థం కాలేదు. '2 కిలో చక్కెర', 'menu', లేదా 'యజమాని' అని పంపవచ్చు.",
        "out_of_stock": "క్షమించండి, {name} ఇప్పుడు స్టాక్‌లో లేదు.",
        "no_info": "ఆ సమాచారం నా దగ్గర లేదు; యజమానికి తెలియజేశాను.",
    },
    "bn": {
        "greet": "নমস্কার! {biz}-এ আপনাকে স্বাগত। কী লাগবে বলুন — যেমন '2 কেজি চিনি'। জিনিসপত্র দেখতে 'menu' লিখুন।",
        "menu_header": "{biz}-এ যা পাওয়া যায়:",
        "added": "{items} যোগ করা হয়েছে। মোট: {total}। অর্ডার করতে 'confirm' লিখুন।",
        "price": "{name}-এর দাম প্রতি {unit} {price}।",
        "not_found": "দুঃখিত, এটা পাওয়া গেল না। জিনিসপত্র দেখতে 'menu' লিখুন।",
        "ambiguous": "আপনি কোনটা চান? {options}",
        "cart_empty": "আপনার কার্ট খালি। কী লাগবে বলুন।",
        "cart": "আপনার কার্ট: {items}। মোট: {total}। অর্ডার করতে 'confirm' লিখুন।",
        "order_placed_upi": "অর্ডার {code} হয়ে গেছে। মোট {total}। নিচের বোতাম দিয়ে UPI-তে পেমেন্ট করুন; টাকা পেলে {biz} নিশ্চিত করবে।",
        "order_placed_cod": "অর্ডার {code} হয়ে গেছে। মোট {total}। ডেলিভারির সময় {biz}-কে টাকা দিন।",
        "paid_claimed": "ধন্যবাদ! আপনি অর্ডার {code}-এর পেমেন্ট করেছেন বলে {biz}-কে জানিয়েছি। ওঁরা শীঘ্রই নিশ্চিত করবেন।",
        "status": "অর্ডার {code}: {status}।",
        "no_orders": "আপনার এখনও কোনো অর্ডার নেই।",
        "hours": "{biz}-এর সময়: {hours}।",
        "location": "{biz}-এর ঠিকানা: {address}",
        "human": "মালিককে উত্তর দিতে বলেছি। উনি শীঘ্রই এখানে উত্তর দেবেন।",
        "cancelled": "অর্ডার {code} বাতিল করা হয়েছে।",
        "cart_cleared": "ঠিক আছে, কার্ট খালি করে দিয়েছি।",
        "cannot_cancel": "অর্ডার {code} এখন {status}; দয়া করে মালিকের সঙ্গে কথা বলুন।",
        "removed": "{items} বাদ দেওয়া হয়েছে। মোট: {total}।",
        "thanks": "ধন্যবাদ! আবার আসবেন।",
        "fallback": "দুঃখিত, বুঝতে পারিনি। আপনি লিখতে পারেন: '2 কেজি চিনি', 'menu', বা 'মালিক'।",
        "out_of_stock": "দুঃখিত, {name} এখন স্টকে নেই।",
        "no_info": "এই তথ্য আমার কাছে নেই; মালিককে জানিয়েছি।",
    },
}

STATUS_NAMES: dict[str, tuple[str, ...]] = {
    "en": ("awaiting payment", "payment being verified", "paid", "being prepared", "ready", "delivered", "cancelled"),
    "hi": ("भुगतान बाकी", "भुगतान की पुष्टि बाकी", "भुगतान मिल गया", "तैयार हो रहा है", "तैयार है", "पहुँच गया", "रद्द"),
    "hi_latn": ("payment baaki", "payment confirm hona baaki", "payment mil gaya", "taiyaar ho raha hai", "taiyaar hai", "pahunch gaya", "cancel"),
    "mr": ("पैसे बाकी", "पैशांची पुष्टी बाकी", "पैसे मिळाले", "तयार होत आहे", "तयार आहे", "पोहोचली", "रद्द"),
    "ta": ("பணம் செலுத்த வேண்டும்", "பணம் சரிபார்க்கப்படுகிறது", "பணம் கிடைத்தது", "தயாராகிறது", "தயார்", "வந்து சேர்ந்தது", "ரத்து"),
    "ta_latn": ("payment pending", "payment check aagudhu", "payment vandhuduchu", "ready aagudhu", "ready", "deliver aayiduchu", "cancel"),
    "te": ("చెల్లింపు పెండింగ్", "చెల్లింపు పరిశీలనలో ఉంది", "చెల్లింపు అందింది", "సిద్ధమవుతోంది", "సిద్ధంగా ఉంది", "డెలివరీ అయింది", "రద్దు"),
    "bn": ("পেমেন্ট বাকি", "পেমেন্ট যাচাই হচ্ছে", "পেমেন্ট পাওয়া গেছে", "তৈরি হচ্ছে", "তৈরি", "পৌঁছে গেছে", "বাতিল"),
}

UNIT_NAMES: dict[str, dict[str, str]] = {
    "en": {"kg": "kg", "l": "litre", "pc": "piece", "pkt": "packet", "g": "g", "dozen": "dozen"},
    "hi": {"kg": "किलो", "l": "लीटर", "pc": "पीस", "pkt": "पैकेट", "g": "ग्राम", "dozen": "दर्जन"},
    "hi_latn": {"kg": "kilo", "l": "litre", "pc": "piece", "pkt": "packet", "g": "gram", "dozen": "darjan"},
    "mr": {"kg": "किलो", "l": "लीटर", "pc": "नग", "pkt": "पॅकेट", "g": "ग्रॅम", "dozen": "डझन"},
    "ta": {"kg": "கிலோ", "l": "லிட்டர்", "pc": "பீஸ்", "pkt": "பாக்கெட்", "g": "கிராம்", "dozen": "டஜன்"},
    "ta_latn": {"kg": "kilo", "l": "litre", "pc": "piece", "pkt": "packet", "g": "gram", "dozen": "dozen"},
    "te": {"kg": "కిలో", "l": "లీటర్", "pc": "పీస్", "pkt": "ప్యాకెట్", "g": "గ్రాము", "dozen": "డజను"},
    "bn": {"kg": "কেজি", "l": "লিটার", "pc": "পিস", "pkt": "প্যাকেট", "g": "গ্রাম", "dozen": "ডজন"},
}

LANG_SCRIPT = {"hi": "Deva", "mr": "Deva", "ta": "Taml", "te": "Telu", "bn": "Beng", "kn": "Knda"}


def template_lang(lang: str) -> str:
    return lang if lang in T else "en"


def t(lang: str, key: str, **kw) -> str:
    return T[template_lang(lang)][key].format(**kw)


def status_name(lang: str, status: str) -> str:
    return STATUS_NAMES[template_lang(lang)][STATUS_KEYS.index(status)]


def unit_name(lang: str, unit: str) -> str:
    return UNIT_NAMES[template_lang(lang)].get(unit, unit)
